// <auto-generated />
using GabbroSecretManager.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GabbroSecretManager.Persistence.Migrations
{
    [DbContext(typeof(SecretsDbContext))]
    partial class SecretsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("GabbroSecretManager.Persistence.Models.SecretSurrogate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("InitializationVector")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Secrets", (string)null);
                });

            modelBuilder.Entity("GabbroSecretManager.Persistence.Models.TagSurrogate", b =>
                {
                    b.Property<long>("SecretId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("SecretId", "Tag");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("GabbroSecretManager.Persistence.Models.TagSurrogate", b =>
                {
                    b.HasOne("GabbroSecretManager.Persistence.Models.SecretSurrogate", "Secret")
                        .WithMany("Tags")
                        .HasForeignKey("SecretId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Secret");
                });

            modelBuilder.Entity("GabbroSecretManager.Persistence.Models.SecretSurrogate", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
