version: '3.9'

services:
  db:
    image: postgres
    networks:
      - gsm-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: IgRbId5kODidpXF9HimuWNWJCsUKIkcMM32yiFbMyqE=
      POSTGRES_USER: gsm 
    shm_size: 128mb
  gsm:
    # image: registry.gitlab.com/haondt/cicd/registry/gabbro-secret-manager:latest
    # build from source:
    build:
      context: ./Gabbro-Secret-Manager/
      dockerfile: ./Gabbro-Secret-Manager/Dockerfile
    container_name: gabbro-secret-manager
    networks:
      - gsm-network
    ports:
      - 8080:8080
    environment:
      JweSettings__EncryptionKey: "QpLMMPrsuRe0vuwTGtQQugfMEeMEvo++mGYACBu4rR4="
      JweSettings__SigningKey: "HuSdq2H1QENlVkk/i8qxJ5EnAvFImb8oHpQGK/4i21Y="
      PersistenceSettings__Driver: postgres
      PostgreSQLSettings__ConnectionString: Host=db;Username=gsm;Password=IgRbId5kODidpXF9HimuWNWJCsUKIkcMM32yiFbMyqE=;Database=gsm

networks:
  gsm-network:
volumes:
  postgres-data:
