services:
  gsm:
    # image: registry.gitlab.com/haondt/cicd/registry/gsm:latest
    # build from source:
    build:
      context: ./Gabbro-Secret-Manager/
      dockerfile: ./GabbroSecretManager/Dockerfile
    container_name: gsm
    ports:
      - 8080:8080
    environment:
      JweSettings__EncryptionKey: "QpLMMPrsuRe0vuwTGtQQugfMEeMEvo++mGYACBu4rR4="
      JweSettings__SigningKey: "HuSdq2H1QENlVkk/i8qxJ5EnAvFImb8oHpQGK/4i21Y="
      GabbroSecretManagerPersistenceSettings__DatabasePath: /data/data.db

  gsm-data-init:
    volumes:
      - gsm-data:/data
    group-add:
      - 80085
    user: root
    image: alpine
    command: >
      sh -c "
        if [ ! -f /data/.initialized ]; then
          chgrp -R 80085 /data && chmod -R 775 /data && touch /data/.initialized;
        fi"

volumes:
  gsm-data: