name: docker
on:
  release:
    types: [published]
    tags: ['v*.*.*']

jobs:
  docker-build-and-push:
    uses: haondt/github-workflows/.github/workflows/ghcr-build-and-push.yml@main
    permissions:
        contents: read
        packages: write
        id-token: write
    secrets: inherit
    with:
      image: Gabbro-Secret-Manager
      repository: haondt
      context: Gabbro-Secret-Manager
      file: Gabbro-Secret-Manager/Gabbro-Secret-Manager/Dockerfile
