name: docker
on:
  release:
    types: [published]
    tags: ['v*.*.*']

jobs:
  docker-build-and-push:
    uses: haondt/github-workflows/.github/workflows/docker-build-and-push.yml@main
    secrets: inherit
    with:
      REGISTRY: ghcr
      IMAGE_NAME: Gabbro-Secret-Manager
      REPOSITORY: haondt
      BUILD_CONTEXT: Gabbro-Secret-Manager
      DOCKERFILE: Gabbro-Secret-Manager/Gabbro-Secret-Manager/Dockerfile
